version: "3.2"

services:

  dev:
    build: .
    volumes:
      - ".:/code"
      - "~/.ssh:/root/.ssh"
      # so that packages are not redownloaded every time, even if we recreate the container
      - "~/.cache:/root/.cache"
